import { config } from "dotenv";

config({ path: `.env.${process.env.NODE_ENV || "development"}.local` });

export const {
  PORT,
  NODE_ENV,
  MONGODB_URI,
  JWT_SECRET,
  JWT_EXEXPIRES_IN,
  SENDER_NAME,
  EMAIL_SERVICE,
  EMAIL_ADDRESS,
  EMAIL_PASSWORD,
  HMAC_SECRET,
  HASH_SALT,
  ARCJET_ENV,
  ARCJET_KEY,
  SURE_MESSAGE,
  QSTASH_URL,
  QSTASH_TOKEN,
  SERVER_URL,
  USERS_DB_URI,
  POSTS_DB_URI,
  SHORTURLS_DB_URI,
  SUBSCRIPTIONS_DB_URI,
  NEWSLETTERS_DB_URI,
  DB_NAME,
  API_KEY_ENCRYPTION_SECRET,
  API_KEY_ENCRYPTION_ALGORITHM,
  API_KEY_ENCRYPTION_IV_LENGTH,
} = process.env;
